name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_TOKEN}}

      - name: Build the Docker image
        # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        run: docker build -t sohis-frontend . --tag eshun/sohis-site:v1.0

      - name: Push to Docker Hub
        run: docker push eshun/sohis-site:v1.0
