name: Docker Image CI

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME}}
          password: ${{ secrets.DOCKER_HUB_TOKEN}}

      - name: Build the Docker image
        # run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
        run: docker build -t sohis-frontend . --tag eshun/sohis-site:v1.0

      - name: Push to Docker Hub
        run: docker push eshun/sohis-site:v1.0

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: SSH In EC2 Instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST_IP_ADDRESS }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            sudo docker system prune --force && \
            sudo docker pull eshun/sohis-site:v1.0 && \
            cd /home/projects/ && \ 
            sudo docker-compose up -d wwm-backend
